CREATE TABLE teknisi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_teknisi VARCHAR(255) NOT NULL,
    alamat TEXT,
    no_hp VARCHAR(15),
    photo VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);